### ISSUE TITLE
error on macos 

### ISSUE THREAD

**Issue by dualra1n** [dora2-iOS/t8015_fakerootfs_homebutton#2]
Darling [/Volumes/SystemRoot/home/edwinnunez/Documentos/ios/t8015_fakerootfs_homebutton/ibootpatch2]$ ./iBootpatch2 --t8010 iBoot.patched iBoot.patchedb
0000000870000000[0000000000000300]: iboot_base
000000087001f1d8[000000000001f1d8]: check_bootmode
000000087004ff77[000000000004ff77]: bootx_str
00000008700527a8[00000000000527a8]: bootx_cmd_handler
00000008700527f8[00000000000527f8]: go_cmd_handler
0000000870000820[0000000000000820]: zeroBuf

**Comment by dora2-iOS** [comment]
i only tested for t8010/t8015 15.7.1. maybe need to fix offsetfinder for A8-A9?

**Comment by dualra1n** [comment]
sir ibec can work with this ? for example patch ibec in order to home button work.
or does this only work for iboot.im4p sir?

**Comment by dualra1n** [comment]
> i only tested for t8010/t8015 15.7.1. maybe need to fix offsetfinder for A8-A9?

but what that will fix on a8-a9? because on a10 and a11 this fix home button, isn't it?

**Comment by dora2-iOS** [comment]
I guess you're trying on a device other than A10-A11...

**Comment by dualra1n** [comment]
@dora2-iOS sorry


> sir ibec can work with this ? for example patch ibec in order to home button work. or does this only work for iboot.im4p sir?

but can we do it ?

**Comment by dora2-iOS** [comment]
I think iBEC and iBoot were some. also it will always behave like iBEC because the patch for this tool forces remote boot

**Comment by dualra1n** [comment]
> I think iBEC and iBoot were some. also it will always behave like iBEC because the patch for this tool forces remote boot

@dora2-iOS sir thank you.

**Comment by dualra1n** [comment]
Hi dori, so about we were talking before so I have a protect which is dualboot, dualboot is having 2 iOS on one device so the problem is that when we boot on a10 and a11 the home button does not work so do you think that this can fix it on iOS 14 with dualboot ?

**Comment by dualra1n** [comment]
And thank you for the tool @dora2-iOS now I see that you are woman xd sorry for named sir
